// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

// ---------------------------------------------------------------------------
import Exchange from './base/Exchange.js';
import { ArgumentsRequired, AuthenticationError, BadRequest, BadResponse, ExchangeError, ExchangeNotAvailable, InsufficientFunds, InvalidAddress, InvalidOrder, NetworkError, NotSupported, NullResponse, OperationFailed, OrderNotFound, PermissionDenied, RateLimitExceeded, RequestTimeout, } from './base/errors.js';
// ---------------------------------------------------------------------------
export default class gmx extends Exchange {
    describe() {
        return this.deepExtend(super.describe(), {
            'id': 'gmx',
            'name': 'GMX',
            'countries': undefined,
            'rateLimit': 2000,
            'certified': false,
            'pro': false,
            'dex': false,
            'has': {
                'CORS': undefined,
                'spot': false,
                'margin': true,
                'swap': true,
                'future': true,
                'option': false,
                'addMargin': true,
                'cancelAllOrders': false,
                'cancelOrder': true,
                'cancelOrders': true,
                'createLimitBuyOrder': true,
                'createLimitOrder': true,
                'createLimitSellOrder': true,
                'createMarketBuyOrder': true,
                'createMarketOrder': true,
                'createMarketSellOrder': true,
                'createOrder': true,
                'editOrder': false,
                'fetchBalance': true,
                'fetchClosedOrders': false,
                'fetchCurrencies': true,
                'fetchFundingHistory': true,
                'fetchFundingRate': true,
                'fetchFundingRateHistory': true,
                'fetchL2OrderBook': false,
                'fetchLeverage': true,
                'fetchLeverageTiers': true,
                'fetchMarketLeverageTiers': true,
                'fetchMarkets': true,
                'fetchMyTrades': true,
                'fetchOHLCV': true,
                'fetchOpenInterest': true,
                'fetchOpenInterestHistory': true,
                'fetchOpenInterests': true,
                'fetchOpenOrders': true,
                'fetchOrder': true,
                'fetchOrderBook': false,
                'fetchOrders': true,
                'fetchPositions': true,
                'fetchStatus': true,
                'fetchTicker': true,
                'fetchTickers': true,
                'fetchTime': true,
                'fetchTrades': true,
                'reduceMargin': true,
                'setLeverage': true,
                'ws': false,
            },
            'urls': {
                'logo': undefined,
                'api': {
                    'rest': 'http://127.0.0.1:8000',
                },
                'www': 'https://gmx.io',
                'doc': [
                    'https://docs.gmx.io/',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'healthz': 1,
                        'describe': 1,
                    },
                },
                'private': {
                    'post': {
                        'call': 1,
                    },
                },
            },
            'requiredCredentials': {
                'apiKey': false,
                'secret': false,
                'uid': false,
                'accountId': false,
                'login': false,
                'password': false,
                'twofa': false,
                'privateKey': false,
                'walletAddress': false,
                'token': false,
            },
            'httpExceptions': {
                '401': AuthenticationError,
                '403': AuthenticationError,
                '408': RequestTimeout,
                '429': RateLimitExceeded,
                '500': ExchangeNotAvailable,
                '503': ExchangeNotAvailable,
            },
            'options': {
                'bridgeUrl': 'http://127.0.0.1:8000',
                'token': undefined,
            },
        });
    }
    getBridgeUrl() {
        const fromInstance = this.safeString2(this, 'bridgeUrl', 'bridgeURL');
        const fromOptions = this.safeString2(this.options, 'bridgeUrl', 'bridgeURL');
        const fromUrls = this.safeString(this.safeDict(this.urls, 'api'), 'rest');
        const url = fromInstance || fromOptions || fromUrls;
        if (url === undefined) {
            throw new ArgumentsRequired(this.id + ' requires bridgeUrl in the constructor');
        }
        return url.replace(/\/+$/, '');
    }
    getBridgeToken() {
        const fromInstance = this.safeString2(this, 'token', 'authToken');
        if (fromInstance !== undefined) {
            return fromInstance;
        }
        const token = this.safeString2(this.options, 'token', 'authToken');
        if (token !== undefined) {
            return token;
        }
        return undefined;
    }
    bridgeMethodName(methodName) {
        return methodName.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
    }
    bridgeErrorToException(error) {
        const errorType = this.safeString(error, 'ccxt_error') || this.safeString(error, 'type') || 'ExchangeError';
        const message = this.safeString(error, 'message') || (this.id + ' bridge request failed');
        const exceptions = {
            'AuthenticationError': AuthenticationError,
            'BadRequest': BadRequest,
            'BadResponse': BadResponse,
            'ExchangeError': ExchangeError,
            'ExchangeNotAvailable': ExchangeNotAvailable,
            'InsufficientFunds': InsufficientFunds,
            'InvalidAddress': InvalidAddress,
            'InvalidOrder': InvalidOrder,
            'NetworkError': NetworkError,
            'NotSupported': NotSupported,
            'NullResponse': NullResponse,
            'OperationFailed': OperationFailed,
            'OrderNotFound': OrderNotFound,
            'PermissionDenied': PermissionDenied,
            'RateLimitExceeded': RateLimitExceeded,
            'RequestTimeout': RequestTimeout,
        };
        const ExceptionClass = this.safeValue(exceptions, errorType, ExchangeError);
        return new ExceptionClass(message);
    }
    async requestBridge(localMethod, args = [], kwargs = {}) {
        const url = this.getBridgeUrl() + '/call';
        const useHttpAgent = url.indexOf('http://') === 0;
        const originalAgent = this.agent;
        if (useHttpAgent) {
            await this.loadHttpProxyAgent();
            this.agent = this.httpAgent;
        }
        const headers = {
            'Content-Type': 'application/json',
        };
        const token = this.getBridgeToken();
        if (token !== undefined) {
            headers['Authorization'] = 'Bearer ' + token;
        }
        const body = this.jsonStringifyWithNull({
            'id': this.numberToString(this.milliseconds()) + '-' + localMethod,
            'method': this.bridgeMethodName(localMethod),
            'args': args,
            'kwargs': kwargs,
        });
        try {
            const response = await this.fetch(url, 'POST', headers, body);
            const ok = this.safeBool(response, 'ok');
            if (!ok) {
                const error = this.safeDict(response, 'error', {});
                throw this.bridgeErrorToException(error);
            }
            return this.safeValue(response, 'result');
        }
        finally {
            if (useHttpAgent) {
                this.agent = originalAgent;
            }
        }
    }
    async fetchMarkets(params = {}) {
        return await this.requestBridge('fetchMarkets', [], { 'params': params });
    }
    async fetchCurrencies(params = {}) {
        return await this.requestBridge('fetchCurrencies', [], { 'params': params });
    }
    async fetchTicker(symbol, params = {}) {
        return await this.requestBridge('fetchTicker', [symbol], { 'params': params });
    }
    async fetchTickers(symbols = undefined, params = {}) {
        return await this.requestBridge('fetchTickers', [symbols], { 'params': params });
    }
    async fetchOHLCV(symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchOHLCV', [symbol, timeframe, since, limit], { 'params': params });
    }
    async fetchTrades(symbol, since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchTrades', [symbol, since, limit], { 'params': params });
    }
    async fetchTime(params = {}) {
        return await this.requestBridge('fetchTime', [], { 'params': params });
    }
    async fetchStatus(params = {}) {
        return await this.requestBridge('fetchStatus', [], { 'params': params });
    }
    async fetchOpenInterest(symbol, params = {}) {
        return await this.requestBridge('fetchOpenInterest', [symbol], { 'params': params });
    }
    async fetchOpenInterestHistory(symbol, timeframe = '1h', since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchOpenInterestHistory', [symbol, timeframe, since, limit], { 'params': params });
    }
    async fetchOpenInterests(symbols = undefined, params = {}) {
        return await this.requestBridge('fetchOpenInterests', [symbols], { 'params': params });
    }
    async fetchFundingRate(symbol, params = {}) {
        return await this.requestBridge('fetchFundingRate', [symbol], { 'params': params });
    }
    async fetchFundingRateHistory(symbol, since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchFundingRateHistory', [symbol, since, limit], { 'params': params });
    }
    async fetchFundingHistory(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchFundingHistory', [symbol, since, limit], { 'params': params });
    }
    async fetchAPY(symbols = undefined, params = {}) {
        return await this.requestBridge('fetchAPY', [symbols], { 'params': params });
    }
    async fetchBalance(params = {}) {
        return await this.requestBridge('fetchBalance', [], { 'params': params });
    }
    async fetchOpenOrders(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchOpenOrders', [symbol, since, limit], { 'params': params });
    }
    async fetchMyTrades(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchMyTrades', [symbol, since, limit], { 'params': params });
    }
    async fetchPositions(symbols = undefined, params = {}) {
        return await this.requestBridge('fetchPositions', [symbols], { 'params': params });
    }
    async fetchMarketLeverageTiers(symbol, params = {}) {
        return await this.requestBridge('fetchMarketLeverageTiers', [symbol], { 'params': params });
    }
    async fetchLeverageTiers(symbols = undefined, params = {}) {
        return await this.requestBridge('fetchLeverageTiers', [symbols], { 'params': params });
    }
    async setLeverage(leverage, symbol = undefined, params = {}) {
        return await this.requestBridge('setLeverage', [leverage, symbol], { 'params': params });
    }
    async fetchLeverage(symbol = undefined, params = {}) {
        return await this.requestBridge('fetchLeverage', [symbol], { 'params': params });
    }
    async addMargin(symbol, amount, params = {}) {
        return await this.requestBridge('addMargin', [symbol, amount], { 'params': params });
    }
    async reduceMargin(symbol, amount, params = {}) {
        return await this.requestBridge('reduceMargin', [symbol, amount], { 'params': params });
    }
    async createOrder(symbol, type, side, amount, price = undefined, params = {}) {
        return await this.requestBridge('createOrder', [symbol, type, side, amount, price], { 'params': params });
    }
    async createMarketBuyOrder(symbol, amount, params = {}) {
        return await this.requestBridge('createMarketBuyOrder', [symbol, amount], { 'params': params });
    }
    async createMarketSellOrder(symbol, amount, params = {}) {
        return await this.requestBridge('createMarketSellOrder', [symbol, amount], { 'params': params });
    }
    async createLimitOrder(symbol, side, amount, price, params = {}) {
        return await this.requestBridge('createLimitOrder', [symbol, side, amount, price], { 'params': params });
    }
    async cancelOrder(id, symbol = undefined, params = {}) {
        return await this.requestBridge('cancelOrder', [id, symbol], { 'params': params });
    }
    async cancelOrders(ids = undefined, symbol = undefined, params = {}) {
        return await this.requestBridge('cancelOrders', [ids, symbol], { 'params': params });
    }
    async fetchOrder(id, symbol = undefined, params = {}) {
        return await this.requestBridge('fetchOrder', [id, symbol], { 'params': params });
    }
    async fetchOrderBook(symbol, limit = undefined, params = {}) {
        return await this.requestBridge('fetchOrderBook', [symbol, limit], { 'params': params });
    }
    async fetchClosedOrders(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchClosedOrders', [symbol, since, limit], { 'params': params });
    }
    async fetchOrders(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        return await this.requestBridge('fetchOrders', [symbol, since, limit], { 'params': params });
    }
}
