# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.gmx import ImplicitAPI
from ccxt.base.types import Any, Balances, Currencies, Int, LeverageTier, Num, Order, OrderSide, OrderType, Position, Str, Strings, Ticker, Tickers, FundingRate, OpenInterest, Trade
from typing import List
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import AuthenticationError
from ccxt.base.errors import PermissionDenied
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.errors import BadRequest
from ccxt.base.errors import InsufficientFunds
from ccxt.base.errors import InvalidAddress
from ccxt.base.errors import InvalidOrder
from ccxt.base.errors import OrderNotFound
from ccxt.base.errors import NotSupported
from ccxt.base.errors import OperationFailed
from ccxt.base.errors import NetworkError
from ccxt.base.errors import RateLimitExceeded
from ccxt.base.errors import ExchangeNotAvailable
from ccxt.base.errors import RequestTimeout
from ccxt.base.errors import BadResponse
from ccxt.base.errors import NullResponse


class gmx(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(gmx, self).describe(), {
            'id': 'gmx',
            'name': 'GMX',
            'countries': None,
            'rateLimit': 2000,
            'certified': False,
            'pro': False,
            'dex': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': True,
                'swap': True,
                'future': True,
                'option': False,
                'addMargin': True,
                'cancelAllOrders': False,
                'cancelOrder': True,
                'cancelOrders': True,
                'createLimitBuyOrder': True,
                'createLimitOrder': True,
                'createLimitSellOrder': True,
                'createMarketBuyOrder': True,
                'createMarketOrder': True,
                'createMarketSellOrder': True,
                'createOrder': True,
                'editOrder': False,
                'fetchBalance': True,
                'fetchClosedOrders': False,
                'fetchCurrencies': True,
                'fetchFundingHistory': True,
                'fetchFundingRate': True,
                'fetchFundingRateHistory': True,
                'fetchL2OrderBook': False,
                'fetchLeverage': True,
                'fetchLeverageTiers': True,
                'fetchMarketLeverageTiers': True,
                'fetchMarkets': True,
                'fetchMyTrades': True,
                'fetchOHLCV': True,
                'fetchOpenInterest': True,
                'fetchOpenInterestHistory': True,
                'fetchOpenInterests': True,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': False,
                'fetchOrders': True,
                'fetchPositions': True,
                'fetchStatus': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': True,
                'fetchTrades': True,
                'reduceMargin': True,
                'setLeverage': True,
                'ws': False,
            },
            'urls': {
                'logo': None,
                'api': {
                    'rest': 'http://127.0.0.1:8000',
                },
                'www': 'https://gmx.io',
                'doc': [
                    'https://docs.gmx.io/',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'healthz': 1,
                        'describe': 1,
                    },
                },
                'private': {
                    'post': {
                        'call': 1,
                    },
                },
            },
            'requiredCredentials': {
                'apiKey': False,
                'secret': False,
                'uid': False,
                'accountId': False,
                'login': False,
                'password': False,
                'twofa': False,
                'privateKey': False,
                'walletAddress': False,
                'token': False,
            },
            'httpExceptions': {
                '401': AuthenticationError,
                '403': AuthenticationError,
                '408': RequestTimeout,
                '429': RateLimitExceeded,
                '500': ExchangeNotAvailable,
                '503': ExchangeNotAvailable,
            },
            'options': {
                'bridgeUrl': 'http://127.0.0.1:8000',
                'token': None,
            },
        })

    def get_bridge_url(self) -> str:
        fromInstance = self.safe_string_2(self, 'bridgeUrl', 'bridgeURL')
        fromOptions = self.safe_string_2(self.options, 'bridgeUrl', 'bridgeURL')
        fromUrls = self.safe_string(self.safe_dict(self.urls, 'api'), 'rest')
        url = fromInstance or fromOptions or fromUrls
        if url is None:
            raise ArgumentsRequired(self.id + ' requires bridgeUrl in the constructor')
        return url.replace(/\/+$/, '')

    def get_bridge_token(self) -> Str:
        fromInstance = self.safe_string_2(self, 'token', 'authToken')
        if fromInstance is not None:
            return fromInstance
        token = self.safe_string_2(self.options, 'token', 'authToken')
        if token is not None:
            return token
        return None

    def bridge_method_name(self, methodName: str) -> str:
        return methodName.replace(/([a-z0-9])([A-Z])/g, '$1_$2').lower()

    def bridge_error_to_exception(self, error) -> Error:
        errorType = self.safe_string(error, 'ccxt_error') or self.safe_string(error, 'type') or 'ExchangeError'
        message = self.safe_string(error, 'message') or (self.id + ' bridge request failed')
        exceptions = {
            'AuthenticationError': AuthenticationError,
            'BadRequest': BadRequest,
            'BadResponse': BadResponse,
            'ExchangeError': ExchangeError,
            'ExchangeNotAvailable': ExchangeNotAvailable,
            'InsufficientFunds': InsufficientFunds,
            'InvalidAddress': InvalidAddress,
            'InvalidOrder': InvalidOrder,
            'NetworkError': NetworkError,
            'NotSupported': NotSupported,
            'NullResponse': NullResponse,
            'OperationFailed': OperationFailed,
            'OrderNotFound': OrderNotFound,
            'PermissionDenied': PermissionDenied,
            'RateLimitExceeded': RateLimitExceeded,
            'RequestTimeout': RequestTimeout,
        }
        ExceptionClass = self.safe_value(exceptions, errorType, ExchangeError)
        return new ExceptionClass(message)

    def request_bridge(self, localMethod: str, args=[], kwargs={}):
        url = self.get_bridge_url() + '/call'
        useHttpAgent = url.find('http://') == 0
        originalAgent = self.agent
        if useHttpAgent:
            self.load_http_proxy_agent()
            self.agent = self.httpAgent
        headers = {
            'Content-Type': 'application/json',
        }
        token = self.get_bridge_token()
        if token is not None:
            headers['Authorization'] = 'Bearer ' + token
        body = self.json_stringify_with_None({
            'id': self.number_to_string(self.milliseconds()) + '-' + localMethod,
            'method': self.bridge_method_name(localMethod),
            'args': args,
            'kwargs': kwargs,
        })
        try:
            response = self.fetch(url, 'POST', headers, body)
            ok = self.safe_bool(response, 'ok')
            if not ok:
                error = self.safe_dict(response, 'error', {})
                raise self.bridge_error_to_exception(error)
            return self.safe_value(response, 'result')
        } finally {
            if useHttpAgent:
                self.agent = originalAgent

    def fetch_markets(self, params={}) -> List[Market]:
        return self.request_bridge('fetchMarkets', [], {'params': params})

    def fetch_currencies(self, params={}) -> Currencies:
        return self.request_bridge('fetchCurrencies', [], {'params': params})

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        return self.request_bridge('fetchTicker', [symbol], {'params': params})

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        return self.request_bridge('fetchTickers', [symbols], {'params': params})

    def fetch_ohlcv(self, symbol: str, timeframe='1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        return self.request_bridge('fetchOHLCV', [symbol, timeframe, since, limit], {'params': params})

    def fetch_trades(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        return self.request_bridge('fetchTrades', [symbol, since, limit], {'params': params})

    def fetch_time(self, params={}) -> float:
        return self.request_bridge('fetchTime', [], {'params': params})

    def fetch_status(self, params={}) -> Any:
        return self.request_bridge('fetchStatus', [], {'params': params})

    def fetch_open_interest(self, symbol: str, params={}) -> OpenInterest:
        return self.request_bridge('fetchOpenInterest', [symbol], {'params': params})

    def fetch_open_interest_history(self, symbol: str, timeframe='1h', since: Int = None, limit: Int = None, params={}) -> List[OpenInterest]:
        return self.request_bridge('fetchOpenInterestHistory', [symbol, timeframe, since, limit], {'params': params})

    def fetch_open_interests(self, symbols: Strings = None, params={}) -> Any:
        return self.request_bridge('fetchOpenInterests', [symbols], {'params': params})

    def fetch_funding_rate(self, symbol: str, params={}) -> FundingRate:
        return self.request_bridge('fetchFundingRate', [symbol], {'params': params})

    def fetch_funding_rate_history(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> Any:
        return self.request_bridge('fetchFundingRateHistory', [symbol, since, limit], {'params': params})

    def fetch_funding_history(self, symbol: str = None, since: Int = None, limit: Int = None, params={}) -> Any:
        return self.request_bridge('fetchFundingHistory', [symbol, since, limit], {'params': params})

    def fetch_apy(self, symbols: Strings = None, params={}) -> Any:
        return self.request_bridge('fetchAPY', [symbols], {'params': params})

    def fetch_balance(self, params={}) -> Balances:
        return self.request_bridge('fetchBalance', [], {'params': params})

    def fetch_open_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        return self.request_bridge('fetchOpenOrders', [symbol, since, limit], {'params': params})

    def fetch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        return self.request_bridge('fetchMyTrades', [symbol, since, limit], {'params': params})

    def fetch_positions(self, symbols: Strings = None, params={}) -> List[Position]:
        return self.request_bridge('fetchPositions', [symbols], {'params': params})

    def fetch_market_leverage_tiers(self, symbol: str, params={}) -> List[LeverageTier]:
        return self.request_bridge('fetchMarketLeverageTiers', [symbol], {'params': params})

    def fetch_leverage_tiers(self, symbols: Strings = None, params={}) -> Any:
        return self.request_bridge('fetchLeverageTiers', [symbols], {'params': params})

    def set_leverage(self, leverage: float, symbol: Str = None, params={}):
        return self.request_bridge('setLeverage', [leverage, symbol], {'params': params})

    def fetch_leverage(self, symbol: Str = None, params={}):
        return self.request_bridge('fetchLeverage', [symbol], {'params': params})

    def add_margin(self, symbol: str, amount: float, params={}):
        return self.request_bridge('addMargin', [symbol, amount], {'params': params})

    def reduce_margin(self, symbol: str, amount: float, params={}):
        return self.request_bridge('reduceMargin', [symbol, amount], {'params': params})

    def create_order(self, symbol: str, type: OrderType, side: OrderSide, amount: float, price: Num = None, params={}) -> Order:
        return self.request_bridge('createOrder', [symbol, type, side, amount, price], {'params': params})

    def create_market_buy_order(self, symbol: str, amount: float, params={}) -> Order:
        return self.request_bridge('createMarketBuyOrder', [symbol, amount], {'params': params})

    def create_market_sell_order(self, symbol: str, amount: float, params={}) -> Order:
        return self.request_bridge('createMarketSellOrder', [symbol, amount], {'params': params})

    def create_limit_order(self, symbol: str, side: OrderSide, amount: float, price: float, params={}) -> Order:
        return self.request_bridge('createLimitOrder', [symbol, side, amount, price], {'params': params})

    def cancel_order(self, id: str, symbol: Str = None, params={}) -> Order:
        return self.request_bridge('cancelOrder', [id, symbol], {'params': params})

    def cancel_orders(self, ids: Strings = None, symbol: Str = None, params={}):
        return self.request_bridge('cancelOrders', [ids, symbol], {'params': params})

    def fetch_order(self, id: str, symbol: Str = None, params={}):
        return self.request_bridge('fetchOrder', [id, symbol], {'params': params})

    def fetch_order_book(self, symbol: str, limit: Int = None, params={}):
        return self.request_bridge('fetchOrderBook', [symbol, limit], {'params': params})

    def fetch_closed_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}):
        return self.request_bridge('fetchClosedOrders', [symbol, since, limit], {'params': params})

    def fetch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}):
        return self.request_bridge('fetchOrders', [symbol, since, limit], {'params': params})
