// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class gmx : Exchange
{
    public gmx (object args = null): base(args) {}

    public async Task<object> publicGetHealthz (object parameters = null)
    {
        return await this.callAsync ("publicGetHealthz",parameters);
    }

    public async Task<object> publicGetDescribe (object parameters = null)
    {
        return await this.callAsync ("publicGetDescribe",parameters);
    }

    public async Task<object> privatePostCall (object parameters = null)
    {
        return await this.callAsync ("privatePostCall",parameters);
    }

}