// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *GmxCore) PublicGetHealthz (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetHealthz", args...)
}

func (this *GmxCore) PublicGetDescribe (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetDescribe", args...)
}

func (this *GmxCore) PrivatePostCall (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostCall", args...)
}
