<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\gmx as Exchange;
use ccxt\ArgumentsRequired;
use \React\Async;
use \React\Promise\PromiseInterface;

class gmx extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'gmx',
            'name' => 'GMX',
            'countries' => null,
            'rateLimit' => 2000,
            'certified' => false,
            'pro' => false,
            'dex' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => true,
                'swap' => true,
                'future' => true,
                'option' => false,
                'addMargin' => true,
                'cancelAllOrders' => false,
                'cancelOrder' => true,
                'cancelOrders' => true,
                'createLimitBuyOrder' => true,
                'createLimitOrder' => true,
                'createLimitSellOrder' => true,
                'createMarketBuyOrder' => true,
                'createMarketOrder' => true,
                'createMarketSellOrder' => true,
                'createOrder' => true,
                'editOrder' => false,
                'fetchBalance' => true,
                'fetchClosedOrders' => false,
                'fetchCurrencies' => true,
                'fetchFundingHistory' => true,
                'fetchFundingRate' => true,
                'fetchFundingRateHistory' => true,
                'fetchL2OrderBook' => false,
                'fetchLeverage' => true,
                'fetchLeverageTiers' => true,
                'fetchMarketLeverageTiers' => true,
                'fetchMarkets' => true,
                'fetchMyTrades' => true,
                'fetchOHLCV' => true,
                'fetchOpenInterest' => true,
                'fetchOpenInterestHistory' => true,
                'fetchOpenInterests' => true,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrderBook' => false,
                'fetchOrders' => true,
                'fetchPositions' => true,
                'fetchStatus' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTime' => true,
                'fetchTrades' => true,
                'reduceMargin' => true,
                'setLeverage' => true,
                'ws' => false,
            ),
            'urls' => array(
                'logo' => null,
                'api' => array(
                    'rest' => 'http://127.0.0.1:8000',
                ),
                'www' => 'https://gmx.io',
                'doc' => array(
                    'https://docs.gmx.io/',
                ),
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'healthz' => 1,
                        'describe' => 1,
                    ),
                ),
                'private' => array(
                    'post' => array(
                        'call' => 1,
                    ),
                ),
            ),
            'requiredCredentials' => array(
                'apiKey' => false,
                'secret' => false,
                'uid' => false,
                'accountId' => false,
                'login' => false,
                'password' => false,
                'twofa' => false,
                'privateKey' => false,
                'walletAddress' => false,
                'token' => false,
            ),
            'httpExceptions' => array(
                '401' => '\\ccxt\\AuthenticationError',
                '403' => '\\ccxt\\AuthenticationError',
                '408' => '\\ccxt\\RequestTimeout',
                '429' => '\\ccxt\\RateLimitExceeded',
                '500' => '\\ccxt\\ExchangeNotAvailable',
                '503' => '\\ccxt\\ExchangeNotAvailable',
            ),
            'options' => array(
                'bridgeUrl' => 'http://127.0.0.1:8000',
                'token' => null,
            ),
        ));
    }

    public function get_bridge_url(): string {
        $fromInstance = $this->safe_string_2($this, 'bridgeUrl', 'bridgeURL');
        $fromOptions = $this->safe_string_2($this->options, 'bridgeUrl', 'bridgeURL');
        $fromUrls = $this->safe_string($this->safe_dict($this->urls, 'api'), 'rest');
        $url = $fromInstance || $fromOptions || $fromUrls;
        if ($url === null) {
            throw new ArgumentsRequired($this->id . ' requires bridgeUrl in the constructor');
        }
        return str_replace(/\/+$/, '', $url);
    }

    public function get_bridge_token(): ?string {
        $fromInstance = $this->safe_string_2($this, 'token', 'authToken');
        if ($fromInstance !== null) {
            return $fromInstance;
        }
        $token = $this->safe_string_2($this->options, 'token', 'authToken');
        if ($token !== null) {
            return $token;
        }
        return null;
    }

    public function bridge_method_name(string $methodName): string {
        return strtolower(str_replace(/([a-z0-9], $methodName)([A-Z])/g, '$1_$2'));
    }

    public function bridge_error_to_exception($error): Error {
        $errorType = $this->safe_string($error, 'ccxt_error') || $this->safe_string($error, 'type') || 'ExchangeError';
        $message = $this->safe_string($error, 'message') || ($this->id . ' bridge request failed');
        $exceptions = array(
            'AuthenticationError' => '\\ccxt\\AuthenticationError',
            'BadRequest' => '\\ccxt\\BadRequest',
            'BadResponse' => '\\ccxt\\BadResponse',
            'ExchangeError' => '\\ccxt\\ExchangeError',
            'ExchangeNotAvailable' => '\\ccxt\\ExchangeNotAvailable',
            'InsufficientFunds' => '\\ccxt\\InsufficientFunds',
            'InvalidAddress' => '\\ccxt\\InvalidAddress',
            'InvalidOrder' => '\\ccxt\\InvalidOrder',
            'NetworkError' => '\\ccxt\\NetworkError',
            'NotSupported' => '\\ccxt\\NotSupported',
            'NullResponse' => '\\ccxt\\NullResponse',
            'OperationFailed' => '\\ccxt\\OperationFailed',
            'OrderNotFound' => '\\ccxt\\OrderNotFound',
            'PermissionDenied' => '\\ccxt\\PermissionDenied',
            'RateLimitExceeded' => '\\ccxt\\RateLimitExceeded',
            'RequestTimeout' => '\\ccxt\\RequestTimeout',
        );
        $ExceptionClass = $this->safe_value($exceptions, $errorType, '\\ccxt\\ExchangeError');
        return new $ExceptionClass ($message);
    }

    public function request_bridge(string $localMethod, $args = [], $kwargs = array ()) {
        return Async\async(function () use ($localMethod, $args, $kwargs) {
            $url = $this->get_bridge_url() . '/call';
            $useHttpAgent = mb_strpos($url, 'http://') === 0;
            $originalAgent = $this->agent;
            if ($useHttpAgent) {
                Async\await($this->load_http_proxy_agent());
                $this->agent = $this->httpAgent;
            }
            $headers = array(
                'Content-Type' => 'application/json',
            );
            $token = $this->get_bridge_token();
            if ($token !== null) {
                $headers['Authorization'] = 'Bearer ' . $token;
            }
            $body = $this->json_stringify_with_null(array(
                'id' => $this->number_to_string($this->milliseconds()) . '-' . $localMethod,
                'method' => $this->bridge_method_name($localMethod),
                'args' => $args,
                'kwargs' => $kwargs,
            ));
            try {
                $response = Async\await($this->fetch($url, 'POST', $headers, $body));
                $ok = $this->safe_bool($response, 'ok');
                if (!$ok) {
                    $error = $this->safe_dict($response, 'error', array());
                    throw $this->bridge_error_to_exception($error);
                }
                return $this->safe_value($response, 'result');
            } finally {
                if ($useHttpAgent) {
                    $this->agent = $originalAgent;
                }
            }
        }) ();
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            return Async\await($this->request_bridge('fetchMarkets', array(), array( 'params' => $params )));
        }) ();
    }

    public function fetch_currencies($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            return Async\await($this->request_bridge('fetchCurrencies', array(), array( 'params' => $params )));
        }) ();
    }

    public function fetch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            return Async\await($this->request_bridge('fetchTicker', array( $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            return Async\await($this->request_bridge('fetchTickers', array( $symbols ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_ohlcv(string $symbol, $timeframe = '1m', ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $timeframe, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchOHLCV', array( $symbol, $timeframe, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_trades(string $symbol, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchTrades', array( $symbol, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_time($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            return Async\await($this->request_bridge('fetchTime', array(), array( 'params' => $params )));
        }) ();
    }

    public function fetch_status($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            return Async\await($this->request_bridge('fetchStatus', array(), array( 'params' => $params )));
        }) ();
    }

    public function fetch_open_interest(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            return Async\await($this->request_bridge('fetchOpenInterest', array( $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_open_interest_history(string $symbol, $timeframe = '1h', ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $timeframe, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchOpenInterestHistory', array( $symbol, $timeframe, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_open_interests(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            return Async\await($this->request_bridge('fetchOpenInterests', array( $symbols ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_funding_rate(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            return Async\await($this->request_bridge('fetchFundingRate', array( $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_funding_rate_history(string $symbol, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchFundingRateHistory', array( $symbol, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_funding_history(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchFundingHistory', array( $symbol, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_apy(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            return Async\await($this->request_bridge('fetchAPY', array( $symbols ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_balance($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            return Async\await($this->request_bridge('fetchBalance', array(), array( 'params' => $params )));
        }) ();
    }

    public function fetch_open_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchOpenOrders', array( $symbol, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_my_trades(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchMyTrades', array( $symbol, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_positions(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            return Async\await($this->request_bridge('fetchPositions', array( $symbols ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_market_leverage_tiers(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            return Async\await($this->request_bridge('fetchMarketLeverageTiers', array( $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_leverage_tiers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            return Async\await($this->request_bridge('fetchLeverageTiers', array( $symbols ), array( 'params' => $params )));
        }) ();
    }

    public function set_leverage(float $leverage, ?string $symbol = null, $params = array ()) {
        return Async\async(function () use ($leverage, $symbol, $params) {
            return Async\await($this->request_bridge('setLeverage', array( $leverage, $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_leverage(?string $symbol = null, $params = array ()) {
        return Async\async(function () use ($symbol, $params) {
            return Async\await($this->request_bridge('fetchLeverage', array( $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function add_margin(string $symbol, float $amount, $params = array ()) {
        return Async\async(function () use ($symbol, $amount, $params) {
            return Async\await($this->request_bridge('addMargin', array( $symbol, $amount ), array( 'params' => $params )));
        }) ();
    }

    public function reduce_margin(string $symbol, float $amount, $params = array ()) {
        return Async\async(function () use ($symbol, $amount, $params) {
            return Async\await($this->request_bridge('reduceMargin', array( $symbol, $amount ), array( 'params' => $params )));
        }) ();
    }

    public function create_order(string $symbol, string $type, string $side, float $amount, ?float $price = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $type, $side, $amount, $price, $params) {
            return Async\await($this->request_bridge('createOrder', array( $symbol, $type, $side, $amount, $price ), array( 'params' => $params )));
        }) ();
    }

    public function create_market_buy_order(string $symbol, float $amount, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $amount, $params) {
            return Async\await($this->request_bridge('createMarketBuyOrder', array( $symbol, $amount ), array( 'params' => $params )));
        }) ();
    }

    public function create_market_sell_order(string $symbol, float $amount, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $amount, $params) {
            return Async\await($this->request_bridge('createMarketSellOrder', array( $symbol, $amount ), array( 'params' => $params )));
        }) ();
    }

    public function create_limit_order(string $symbol, string $side, float $amount, float $price, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $side, $amount, $price, $params) {
            return Async\await($this->request_bridge('createLimitOrder', array( $symbol, $side, $amount, $price ), array( 'params' => $params )));
        }) ();
    }

    public function cancel_order(string $id, ?string $symbol = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($id, $symbol, $params) {
            return Async\await($this->request_bridge('cancelOrder', array( $id, $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function cancel_orders(?array $ids = null, ?string $symbol = null, $params = array ()) {
        return Async\async(function () use ($ids, $symbol, $params) {
            return Async\await($this->request_bridge('cancelOrders', array( $ids, $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_order(string $id, ?string $symbol = null, $params = array ()) {
        return Async\async(function () use ($id, $symbol, $params) {
            return Async\await($this->request_bridge('fetchOrder', array( $id, $symbol ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_order_book(string $symbol, ?int $limit = null, $params = array ()) {
        return Async\async(function () use ($symbol, $limit, $params) {
            return Async\await($this->request_bridge('fetchOrderBook', array( $symbol, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_closed_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()) {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchClosedOrders', array( $symbol, $since, $limit ), array( 'params' => $params )));
        }) ();
    }

    public function fetch_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()) {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            return Async\await($this->request_bridge('fetchOrders', array( $symbol, $since, $limit ), array( 'params' => $params )));
        }) ();
    }
}
