<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class gmx extends \ccxt\Exchange {
    public function public_get_healthz($params = array()) {
        return $this->request('healthz', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_describe($params = array()) {
        return $this->request('describe', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_post_call($params = array()) {
        return $this->request('call', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function publicGetHealthz($params = array()) {
        return $this->request('healthz', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetDescribe($params = array()) {
        return $this->request('describe', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privatePostCall($params = array()) {
        return $this->request('call', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
}
